FROM node:22.17.1-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa de producción (sirviendo el build)
FROM nginx:alpine

# Copiar build al nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Usar la configuración por defecto de nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
